### PR TITLE
Exponential number format conversion from mma to py added to ToSympy

### PR DESCRIPTION
**Pull request by augsteinboson**

### CODE REVIEW

**Comment by magv** [comment]
Hi, Augustin. The change looks good, but could you squash (and rebase) the commits? Making four commits to change one line is a bit too much :)

**Comment by augsteinboson** [comment]
Hi Vitaly,
can you maybe just copy that line? I think I just messed up my repository big time with the squashing.

**Comment by magv** [comment]
I'll do that, but messing up the git repo is such a common occurrence that fixing it is an important skill in science :)

**Comment by augsteinboson** [comment]
O.K., I'll keep it conserved in the broken state until I figured out how to repair it.
(This condition is obviously divergent in time.)

**Pull request closed without merging**
