### PR TITLE
Add option to use additional filters for qgraf in Diagrams[...]

### PR DESCRIPTION
**Pull request by augsteinboson**
A new option is added to allow usage of additional filters, e.g. employing v_functions, during diagram generation with qgraf, for further details refer to secs. 18 & 19 in the QGRAF 4.0 manual.

A new variable `$QGrafFilter` and a new option are added to the function `Diagrams[...]` in `alibrary.m`. The function is backwards compatible and also works without setting the new option.

### CODE REVIEW

**Comment by augsteinboson** [comment]
Sorry again, for the many commits. They are mainly merges and I did not manage to get rid of them by squashing. I read that supposedly during the pull request it is possible to also squash them away, but I don't see this option.

**Comment by magv** [comment]
Hi, Augustin. I propose to rename it `$QGrafExtra`, because who knows what other things might go into that part of the QGraf config in the future. Please clean up the history: you don't need 7 commits to change 5 lines of code. You should be able to make it a single commit. I'll merge it once you do.

**Comment by augsteinboson** [comment]
Yes, I know that I don't need all them commits. However, I wasted too much time already with this nonsense, which rather not repeat anytime in the next weeks. I might try to make a new pull request later this year, if I have had some time to figure this out and you did not add the option yourself already.

**Comment by magv** [comment]
I think the lesson is not to try to fix git, but rather to work around it (just as we work around a dozen of other broken tools in this very library):
```shell
git clone git@github.com:magv/alibrary.git
cd alibrary
wget 'https://patch-diff.githubusercontent.com/raw/magv/alibrary/pull/8.diff'
patch -p0 <8.diff
git commit -va
git push
```

Anyway, thanks for the contribution, I hope you'll find the result useful.

**Pull request closed without merging**
